In [1]:
import torch
import numpy as np

## Задание 2: Автоматическое дифференцирование

2.1 Простые вычисления с градиентами

In [ ]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([4., 5.], requires_grad=True)
z = torch.tensor([6., 7.], requires_grad=True)

print(f'Исходные векторы \nx:\n{x.detach()}, \ny:\n{y.detach()}, \nz:\n{z.detach()}')
print(f'\nГрадиенты: [ {x.grad}, {y.grad}, {z.grad} ]') # Будут None, т.к ещё не была посчитана функция


f = (x**2 + y**2 + z**2 + 2*x*y*z).sum() # f = f(x, y, z)
f.backward()

print(f"df/dx = {x.grad}")
print(f"df/dy = {y.grad}") 
print(f"df/dz = {z.grad}")

# Вычисление аналитически
x_grad = 2*x + 2*y*z
y_grad = 2*y + 2*x*z
z_grad = 2*z + 2*x*y

print(f"\ndf/dx = {x_grad.detach()}") 
print(f"df/dy = {y_grad.detach()}") 
print(f"df/dz = {z_grad.detach()}")


Исходные векторы 
x:
tensor([2., 3.]), 
y:
tensor([4., 5.]), 
z:
tensor([6., 7.])

Градиенты: [ None, None, None ]
df/dx = tensor([52., 76.])
df/dy = tensor([32., 52.])
df/dz = tensor([28., 44.])

df/dx = tensor([52., 76.])
df/dy = tensor([32., 52.])
df/dz = tensor([28., 44.])


2.2 Градиент функции потерь

In [155]:
# MSE = (1/n) * Σ(y_pred - y_true)^2


def my_mse(y_pred, y_true):
    if not isinstance(y_pred, torch.Tensor) and not isinstance(y_true, torch.Tensor):
        raise TypeError("Invalid type")    
    return (((y_pred - y_true) ** 2)).sum() / y_true.size()[0]


x = torch.arange(10., 20.)
y_true = torch.arange(12., 22.)

print(x)
print(y_true)

w = torch.tensor(1.0, requires_grad=True) 
b = torch.tensor(0.0, requires_grad=True)

y_pred = w * x + b
mse = my_mse(y_pred, y_true)
mse.backward()

print(f'\nMSE: {mse.detach()}')
print(f'Градиент w: {w.grad}') 
print(f'Градиент b: {b.grad}')

tensor([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])
tensor([12., 13., 14., 15., 16., 17., 18., 19., 20., 21.])

MSE: 4.0
Градиент w: -58.0
Градиент b: -4.000000476837158


2.3 Цепное правило

In [156]:
# Реализуйте составную функцию: f(x) = sin(x^2 + 1)
# Найдите градиент df/dx
# Проверьте результат с помощью torch.autograd.grad

x = torch.tensor([12., 53.2, 41.4, 84.1], requires_grad=True)
f = torch.sin(x**2 + 1).sum()

# f(x) = sin(x^2 + 1) -> df/dx = 2xcos(x^2 + 1)

test = 2*x * torch.cos(x**2 + 1)
print(f'Аналитическое решение: \n{test.detach()}')

f.backward()
print(f'\nАвтоградиент: \n{x.grad}')

# проверка torch.autograd.grad
x = torch.tensor([12., 53.2, 41.4, 84.1], requires_grad=True)
f = torch.sin(x**2 + 1).sum()

ag = torch.autograd.grad(outputs=f, inputs=x)

print(f'\ntorch.autograd.grad: \n{ag}')


Аналитическое решение: 
tensor([ 21.2127, -83.7273,  77.7941,  82.6556])

Автоградиент: 
tensor([ 21.2127, -83.7273,  77.7941,  82.6556])

torch.autograd.grad: 
(tensor([ 21.2127, -83.7273,  77.7941,  82.6556]),)
