In [36]:
import torch
import numpy as np

## Задание 1: Создание и манипуляции с тензорами 

### 1.1 Создание тензоров

In [37]:
def create_four_tensors():
    t1 = torch.rand(3, 4) # двумерный массив 3x4
    t2 = torch.zeros(2, 3, 4) # трехмерный массив 3x4, заполненный нулями
    t3 = torch.ones(5, 5) # двумерный массив 5x5, заполненный единицами
    t4 = torch.arange(16.).reshape((4, 4)) # массив 0-15 с reshape 4x4 и float32 типом
    return t1, t2, t3, t4

a, b, c, d = create_four_tensors()

print(f'Двумерный: \n{a}')
print(f'\nТрехмерный 3x4 с нулями: \n{b}')
print(f'\nДвумерный массив 5x5, заполненный единицами: \n{c}')
print(f'\nМассив 0-15 с reshape 4x4 и float32 типом: \n{d}')

Двумерный: 
tensor([[0.8963, 0.6199, 0.9785, 0.0402],
        [0.6567, 0.1117, 0.4118, 0.1315],
        [0.6272, 0.8070, 0.2905, 0.5420]])

Трехмерный 3x4 с нулями: 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Двумерный массив 5x5, заполненный единицами: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Массив 0-15 с reshape 4x4 и float32 типом: 
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


### 1.2 Операции с тензорами

Транспонирование матрицы

In [ ]:
def transpose_matrix(A):
    if not isinstance(A, torch.Tensor):
        raise TypeError("Invalid type")
    return A.T


a = torch.rand(4, 3)
print(f'Исходная матрица: \n{a}')
print(f'\nТранспонированная: {transpose_matrix(a)}')

Исходная матрица: 
tensor([[0.0116, 0.1566, 0.4129],
        [0.4534, 0.9437, 0.7833],
        [0.8891, 0.3717, 0.8419],
        [0.6606, 0.6194, 0.4959]])

Транспонированная: tensor([[0.0116, 0.4534, 0.8891, 0.6606],
        [0.1566, 0.9437, 0.3717, 0.6194],
        [0.4129, 0.7833, 0.8419, 0.4959]])


Матричное умножение

In [ ]:
def matrix_mul(A, B):
    if not isinstance(A, torch.Tensor) and not isinstance(B, torch.Tensor):
        raise TypeError("Invalid type")
    return A @ B

a = torch.rand(3, 4)
b = torch.rand(4, 3)

print(f'\nМатрица a: \n{a}')
print(f'\nМатрица b: \n{b}')
print(f'\na@b: \n{matrix_mul(a, b)}')


Матрица a: 
tensor([[0.5591, 0.0442, 0.7951, 0.1781],
        [0.5692, 0.2666, 0.9217, 0.0535],
        [0.3052, 0.7576, 0.1458, 0.5073]])

Матрица b: 
tensor([[0.6582, 0.8432, 0.1643],
        [0.5839, 0.8181, 0.9110],
        [0.0606, 0.4246, 0.5689],
        [0.0157, 0.4904, 0.8229]])

a@b: 
tensor([[0.4448, 0.9325, 0.7310],
        [0.5870, 1.1157, 0.9048],
        [0.6601, 1.1879, 1.2408]])


Поэлементное умножение A и транспонированного B

In [ ]:
def matrix_el_mul_with_transpose(A, B):
    if not isinstance(A, torch.Tensor) and not isinstance(B, torch.Tensor):
        raise TypeError("Invalid type")
    return A * B.T

print(f'\nМатрица a: \n{a}')
print(f'\nМатрица b: \n{b}')
print(f'\na*b.T: \n{matrix_el_mul_with_transpose(a, b)}')


Матрица a: 
tensor([[0.5591, 0.0442, 0.7951, 0.1781],
        [0.5692, 0.2666, 0.9217, 0.0535],
        [0.3052, 0.7576, 0.1458, 0.5073]])

Матрица b: 
tensor([[0.6582, 0.8432, 0.1643],
        [0.5839, 0.8181, 0.9110],
        [0.0606, 0.4246, 0.5689],
        [0.0157, 0.4904, 0.8229]])

a*b.T: 
tensor([[0.3680, 0.0258, 0.0482, 0.0028],
        [0.4800, 0.2181, 0.3914, 0.0262],
        [0.0501, 0.6902, 0.0830, 0.4175]])


Вычислите сумму всех элементов тензора A

In [ ]:
tensor_sum = torch.randint(1, 10, (3, 4, 4)) # трехмерный массив целых чисел с диапазоном 1-10
print(f'Исходная матрица: \n{tensor_sum}')
print(f'Сумма: {tensor_sum.sum()}')

Исходная матрица: 
tensor([[[3, 2, 2, 9],
         [6, 5, 9, 6],
         [5, 6, 9, 8],
         [8, 3, 7, 1]],

        [[9, 5, 4, 4],
         [8, 4, 1, 4],
         [4, 9, 3, 6],
         [6, 3, 6, 9]],

        [[4, 1, 2, 2],
         [5, 6, 1, 2],
         [6, 8, 6, 1],
         [9, 2, 2, 8]]])
Сумма: 239


### 1.3 Индексация и срезы

In [42]:
t = torch.randint(1, 5, (5, 5, 5))
print("Исходный массив:")
print(t, end='\n')

Исходный массив:
tensor([[[2, 4, 3, 1, 4],
         [1, 3, 3, 4, 4],
         [1, 3, 3, 3, 3],
         [3, 3, 3, 1, 2],
         [2, 3, 2, 3, 3]],

        [[1, 3, 2, 1, 2],
         [3, 1, 2, 2, 4],
         [4, 1, 2, 3, 2],
         [2, 1, 4, 3, 1],
         [3, 3, 1, 4, 2]],

        [[4, 2, 4, 3, 1],
         [3, 1, 2, 1, 4],
         [3, 2, 3, 2, 1],
         [4, 1, 2, 2, 1],
         [4, 4, 1, 1, 1]],

        [[1, 1, 1, 4, 3],
         [2, 3, 2, 4, 2],
         [3, 4, 2, 2, 4],
         [4, 1, 1, 4, 2],
         [2, 3, 4, 4, 2]],

        [[4, 3, 2, 2, 2],
         [2, 4, 1, 4, 2],
         [1, 3, 1, 3, 1],
         [2, 1, 4, 2, 1],
         [1, 2, 3, 1, 2]]])


Извлеките:

In [43]:
print(f'\nПервая строка: \n{t[0, 0]}')
print(f'\nПоследний столбец: \n{t[4, :, 4]}') # -> или можно print(t[4].T[4])
print(f'\n3 матрица с индексами 1-3: \n{t[2, 1:3, 1:3]}') #

print(f'\nчетные индексы: \n{t[::2, ::2, ::2]}')


Первая строка: 
tensor([2, 4, 3, 1, 4])

Последний столбец: 
tensor([2, 2, 1, 1, 2])

3 матрица с индексами 1-3: 
tensor([[1, 2],
        [2, 3]])

четные индексы: 
tensor([[[2, 3, 4],
         [1, 3, 3],
         [2, 2, 3]],

        [[4, 4, 1],
         [3, 3, 1],
         [4, 1, 1]],

        [[4, 2, 2],
         [1, 1, 1],
         [1, 3, 2]]])


### 1.4 Работа с формами

In [51]:
tensor24 = torch.rand(24)

print(f'Исходная матрица: \n{tensor24}')
print(f'\nПреобразования: \n2x12 \n{tensor24.reshape(2, 12)}')
print(f'\n3x8 \n{tensor24.reshape(3, 8)}')
print(f'\n4x6 \n{tensor24.reshape(4, 6)}')
print(f'\n2x3x4 \n{tensor24.reshape(2, 3, 4)}')
print(f'\n2x2x2x3 \n{tensor24.reshape(2, 2, 2, 3)}')


Исходная матрица: 
tensor([0.0244, 0.2245, 0.0978, 0.9828, 0.7402, 0.9244, 0.2645, 0.2983, 0.0902,
        0.1510, 0.4991, 0.5833, 0.4709, 0.8671, 0.8964, 0.6004, 0.5300, 0.7633,
        0.8309, 0.9038, 0.6701, 0.6199, 0.1776, 0.6087])

Преобразования: 
2x12 
tensor([[0.0244, 0.2245, 0.0978, 0.9828, 0.7402, 0.9244, 0.2645, 0.2983, 0.0902,
         0.1510, 0.4991, 0.5833],
        [0.4709, 0.8671, 0.8964, 0.6004, 0.5300, 0.7633, 0.8309, 0.9038, 0.6701,
         0.6199, 0.1776, 0.6087]])

3x8 
tensor([[0.0244, 0.2245, 0.0978, 0.9828, 0.7402, 0.9244, 0.2645, 0.2983],
        [0.0902, 0.1510, 0.4991, 0.5833, 0.4709, 0.8671, 0.8964, 0.6004],
        [0.5300, 0.7633, 0.8309, 0.9038, 0.6701, 0.6199, 0.1776, 0.6087]])

4x6 
tensor([[0.0244, 0.2245, 0.0978, 0.9828, 0.7402, 0.9244],
        [0.2645, 0.2983, 0.0902, 0.1510, 0.4991, 0.5833],
        [0.4709, 0.8671, 0.8964, 0.6004, 0.5300, 0.7633],
        [0.8309, 0.9038, 0.6701, 0.6199, 0.1776, 0.6087]])

2x3x4 
tensor([[[0.0244, 0.2245, 0.0978,